var traces = ["Daily Life", "Hamsters?", "Nuts", "Anchovies", "...stuff?"]

var comics =
[
	{id: '0',chapter:"The Begining", title:"Title", Link:'Comics/01-The Begining/coverbeginning.jpg'},
	{id: '1',chapter:"The Begining", title:"The Begining", Link:'Comics/01-The Begining/Page 1.jpg'},
	{id: '2',chapter:"The Begining", title:"The Skrad", Link:'Comics/01-The Begining/Page 2.jpg'},
	{id: '3',chapter:"The Begining", title:"The Crew", Link:'Comics/01-The Begining/Page 3.jpg'},
	{id: '4',chapter:"The Begining", title:"First Day", Link:'Comics/01-The Begining/Page 4.jpg'},
	{id: '5',chapter:"The Begining", title:"Assigning", Link:'Comics/01-The Begining/Page 5.jpg'},
	{id: '6',chapter:"The Begining", title:"Go Team", Link:'Comics/01-The Begining/Page 6.jpg'},
	{id: '7',chapter:"The Begining", title:"Meany Head", Link:'Comics/01-The Begining/Page 7.jpg'},
	{id: '8',chapter:"The Begining", title:"Suiting Up", Link:'Comics/01-The Begining/Page 8.jpg'},
	{id: '9',chapter:"The Begining", title:"Junkedy Junk", Link:'Comics/01-The Begining/Page 9.jpg'},
	{id: '10',chapter:"The Begining", title:"Beacon", Link:'Comics/01-The Begining/Page 10.jpg'},
	{id: '11',chapter:"The Begining", title:"Always Works", Link:'Comics/01-The Begining/Page 11.jpg'},
	{id: '12',chapter:"The Begining", title:"Orders", Link:'Comics/01-The Begining/Page 12.jpg'},
	{id: '13',chapter:"The Begining", title:"Crush like Rats", Link:'Comics/01-The Begining/Page 13.jpg'},
	{id: '14',chapter:"The Begining", title:"Perfect Opportunity", Link:'Comics/01-The Begining/Page 14.jpg'},
	{id: '15',chapter:"The Begining", title:"Bug Spray", Link:'Comics/01-The Begining/Page 15.jpg'},
	{id: '16',chapter:"The Begining", title:"Mean no harm", Link:'Comics/01-The Begining/Page 16.jpg'},
	{id: '17',chapter:"The Begining", title:"Needing Drinks", Link:'Comics/01-The Begining/Page 17.jpg'},
	{id: '18',chapter:"The Begining", title:"Mission Compleate", Link:'Comics/01-The Begining/Page 18.jpg'},
	{id: '19',chapter:"The Begining", title:"Now Im in charge", Link:'Comics/01-The Begining/Page 19.jpg'},
	{id: '20',chapter:"The Begining", title:"Games", Link:'Comics/01-The Begining/Page 20.jpg'},
	{id: '21',chapter:"The Begining", title:"Idiot", Link:'Comics/01-The Begining/Page 21.jpg'},
	{id: '22',chapter:"The Begining", title:"Tracing the Captain", Link:'Comics/01-The Begining/Page 23.jpg'},
	{id: '23',chapter:"The Begining", title:"High Score", Link:'Comics/01-The Begining/Page 24.jpg'},
	{id: '24',chapter:"The Begining", title:"Weapon of Something", Link:'Comics/01-The Begining/Page 25.jpg'},
	{id: '25',chapter:"The Begining", title:"The leader of the Hive", Link:'Comics/01-The Begining/Page 26.jpg'},
	{id: '26',chapter:"The Begining", title:"Enterin Secret like", Link:'Comics/01-The Begining/Page 27.jpg'},
	{id: '27',chapter:"The Begining", title:"Missile Launch", Link:'Comics/01-The Begining/Page 28.jpg'},
	{id: '28',chapter:"The Begining", title:"Missile Jam", Link:'Comics/01-The Begining/Page 29.jpg'},
	{id: '29',chapter:"The Begining", title:"Crash Land", Link:'Comics/01-The Begining/Page 30.jpg'},
	{id: '30',chapter:"The Begining", title:"Shirt Spoiled", Link:'Comics/01-The Begining/Page 31.jpg'},
	{id: '31',chapter:"The Begining", title:"Oh right... The Missile", Link:'Comics/01-The Begining/Page 32.jpg'},
	{id: '32',chapter:"The Begining", title:"Finding Glasses", Link:'Comics/01-The Begining/Page 33.jpg'},
	{id: '33',chapter:"The Begining", title:"Comunication Issues", Link:'Comics/01-The Begining/Page 34.jpg'},
	{id: '33',chapter:"The Begining", title:"The Krad Leader", Link:'Comics/01-The Begining/Page 35.jpg'},
	{id: '34',chapter:"The Begining", title:"Place to eat you", Link:'Comics/01-The Begining/Page 36.jpg'},
	{id: '35',chapter:"The Begining", title:"All Settled", Link:'Comics/01-The Begining/Page 37.jpg'},
	{id: '36',chapter:"The Begining", title:"The fall of the Skrad", Link:'Comics/01-The Begining/Page 38.jpg'},
	{id: '37',chapter:"The Begining", title:"Going to Plan", Link:'Comics/01-The Begining/Page 38andahalf.jpg'},
	{id: '38',chapter:"The Begining", title:"Bendy Bars", Link:'Comics/01-The Begining/Page 29.jpg'},
	{id: '39',chapter:"The Begining", title:"Soon to arrive", Link:'Comics/01-The Begining/Page 40.jpg'},
	{id: '40',chapter:"The Begining", title:"Hear something", Link:'Comics/01-The Begining/Page 41.jpg'},
	{id: '41',chapter:"The Begining", title:"It's probably nothing", Link:'Comics/01-The Begining/Page 42.jpg'},
	{id: '42',chapter:"The Begining", title:"Figured it out", Link:'Comics/01-The Begining/Page 43.jpg'},
	{id: '43',chapter:"The Begining", title:"Needs testing", Link:'Comics/01-The Begining/Page 44.jpg'},
	{id: '44',chapter:"The Begining", title:"Even better ", Link:'Comics/01-The Begining/Page 45.jpg'},
	{id: '45',chapter:"The Begining", title:"Can't swim", Link:'Comics/01-The Begining/Page 46.jpg'},
	{id: '46',chapter:"The Begining", title:"Tammys Advice ", Link:'Comics/01-The Begining/Page 47.jpg'},
	{id: '47',chapter:"The Begining", title:"Over there ", Link:'Comics/01-The Begining/Page 48.jpg'},
	{id: '48',chapter:"The Begining", title:"Abandoned Bunker", Link:'Comics/01-The Begining/Page 49.jpg'},
	{id: '49',chapter:"The Begining", title:"To war", Link:'Comics/01-The Begining/Page 50.jpg'},
	{id: '50',chapter:"The Begining", title:"Secret Weapon", Link:'Comics/01-The Begining/Page 51.jpg'},
	{id: '51',chapter:"The Begining", title:"Tactfull Handling", Link:'Comics/01-The Begining/Page 52.jpg'},
	{id: '52',chapter:"The Begining", title:"Not our enemy", Link:'Comics/01-The Begining/Page 53.jpg'},
	{id: '53',chapter:"The Begining", title:"All taken care of", Link:'Comics/01-The Begining/Page 54.jpg'},
	{id: '54',chapter:"The Begining", title:"Had enough", Link:'Comics/01-The Begining/Page 55.jpg'},
	{id: '55',chapter:"The Begining", title:"In here", Link:'Comics/01-The Begining/Page 56.jpg'},
	{id: '56',chapter:"The Begining", title:"Skrad ship", Link:'Comics/01-The Begining/Page 57.jpg'},
	{id: '57',chapter:"The Begining", title:"Can't fly it", Link:'Comics/01-The Begining/Page 58.jpg'},
	{id: '58',chapter:"The Begining", title:"Rewired", Link:'Comics/01-The Begining/Page 59.jpg'},
	{id: '59',chapter:"The Begining", title:"Wrong wire", Link:'Comics/01-The Begining/Page 60.jpg'},
	{id: '60',chapter:"The Begining", title:"Gained control", Link:'Comics/01-The Begining/Page 61.jpg'},
	{id: '61',chapter:"The Begining", title:"Home dry", Link:'Comics/01-The Begining/Page 62.jpg'},
	{id: '62',chapter:"The Begining", title:"Impending doom", Link:'Comics/01-The Begining/Page 63.jpg'},
	{id: '63',chapter:"The Begining", title:"Dunno sir", Link:'Comics/01-The Begining/Page 64.jpg'},
	{id: '64',chapter:"The Begining", title:"Going to hurt", Link:'Comics/01-The Begining/Page 65.jpg'},
	{id: '65',chapter:"The Begining", title:"Priorities", Link:'Comics/01-The Begining/Page 66.jpg'},
	{id: '66',chapter:"The Begining", title:"Nothing can stop us", Link:'Comics/01-The Begining/Page 67.jpg'},
	{id: '67',chapter:"The Begining", title:"Just show me", Link:'Comics/01-The Begining/Page 68.jpg'},
	{id: '68',chapter:"The Begining", title:"Need a moment", Link:'Comics/01-The Begining/Page 69.jpg'},
	{id: '69',chapter:"The Begining", title:"Necessary", Link:'Comics/01-The Begining/Page 70.jpg'},
];